### ISSUE TITLE
Test this on Windows

### ISSUE THREAD

**Issue by ocefpaf** [ocefpaf/boston_light_swim#11]
After [this](https://github.com/ocefpaf/boston_light_swim/commit/0dcafb63438adcae659fe4cce2254a2a846064a8) commit the notebooks should run on Windows.

@rsignell-usgs can you test it later?

**Comment by rsignell-usgs** [comment]
01-skill fails with
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6b625f0550a1> in <module>()
      9 fname = os.path.join(run_name, 'config.pkl')
     10 with open(fname, 'rb') as f:
---> 11     config = pickle.load(f)

ImportError: No module named datetime
```
looks like this could be the solution:
http://stackoverflow.com/questions/12412959/pickle-dependency-failure

**Comment by ocefpaf** [comment]
I would not expect that with a standard library module... (anti-MS mode on) but it is Windows and I guess we should not be surprised (anti-MS mode off).

Anyway I want to move away from pickle and store that information in a plain text config file.  (See  #12)

**Comment by ocefpaf** [comment]
Reasons why I love Windows:

![error](https://cloud.githubusercontent.com/assets/950575/9312028/a2ecc796-44f0-11e5-95ba-a27572507839.png)


I will make the modifications in [here](http://stackoverflow.com/questions/12412959/pickle-dependency-failure), test on Linux, and rely on @rsignell-usgs to test them on Windows.

**Comment by ocefpaf** [comment]
[Latest commit](https://github.com/ocefpaf/boston_light_swim/commit/6765d545a814047ca413e5554a25d4b6c5cc9390) unpickles with `'rU'` and that is OK on Linux.  Hopefully it will fixes the notebooks for Windows.

PS: I also changed to zoom level to show all the stations found.

**Comment by rsignell-usgs** [comment]
Grrr, I can't test at all today because of disk problems on the server at SMAST.   They hope to have the bad disk replaced later this week.
