### ISSUE TITLE
Use binder to run the notebooks

### ISSUE THREAD

**Issue by ocefpaf** [ocefpaf/boston_light_swim#16]
@rsignell-usgs everything works just fine.  The files are save in the same instance of the notebook, so bare in mind that the number of the `binder` instance must be the same (see the red circle in the image below).  Sometimes, when clicking multiple times in the `binder` badge we may accidentally open more than 1 instance. 

![snapshot1](https://cloud.githubusercontent.com/assets/950575/10053518/f75d3034-6202-11e5-98dc-c66f77cf233c.png)

**Comment by rsignell-usgs** [comment]
close this?
