### ISSUE TITLE
Update the notebook and binder

### ISSUE THREAD

**Issue by ocefpaf** [ocefpaf/boston_light_swim#19]
@rsignell-usgs I need to modify the notebook with a lot of new syntax changes in `iris` and `pandas`before updating the `binder`. So don't use this until then!

(Doing it now, should be OK in a few hours.)

**Comment by rsignell-usgs** [comment]
Okay!

**Comment by ocefpaf** [comment]
To do list:

- [X] update pandas syntax in utilities;
- [X] re-add ioos channel in the `environment.yaml` (I am not adding utilities to conda-forge yet.);
- [X] update the environment to install `jupyer` instead of `ipython-notebook`;
- [ ] new release and build of utilities in ioos;
- [ ] update notebook to latest folium syntax.

Bônus: update plots to use [`bokeh`](https://github.com/ocefpaf/sscsw) instead of `mpld3`.

**Comment by ocefpaf** [comment]
@rsignell-usgs the binder is back online and working. However, it is not finding any useful data when run against current dates.

If you run against the old dates for the Boston Light Swim it will find COAST and HYCOM, but the FVCOM data is gone.
