### ISSUE TITLE
Reasons why we need to apply this workflow for different regions

### ISSUE THREAD

**Issue by ocefpaf** [ocefpaf/boston_light_swim#5]
Thanks to this exercise we fixed:

- https://github.com/pyoceans/utilities/pull/69
- https://github.com/pyoceans/utilities/pull/70
- https://github.com/pyoceans/utilities/pull/72
- https://github.com/pyoceans/tardis/pull/13
- https://github.com/pyoceans/tardis/pull/14
- https://github.com/pyoceans/tardis/pull/16

And we opened:
- https://github.com/ioos/secoora/issues/204
- https://github.com/ioos/secoora/issues/205

**Comment by rsignell-usgs** [comment]
Epic.   And we documented a real bias issue with two of our models: COAWST is nearly 2 degC warmer than the observations and the NECOFS MassBay Model is nearly 2 degC colder:
![2015-08-11_1841](https://cloud.githubusercontent.com/assets/1872600/9214708/fe7429d2-406e-11e5-8577-fe97affc6b01.png)

Those are huge differences for ocean swimmers!

**Comment by ocefpaf** [comment]
Just to show off: if the water temperature is around 24 degC here people call it "winter."

**Comment by ocefpaf** [comment]
We have the `sscsw` notebook for this. (Adding it to ioos/notebooks_demos soon.)
